variables:
    SolutionBaseName: 'DFC.EventGridSubscriptions.ApiFunction'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

pool:
  name: NCS - CI and CD
  demands:
    - msbuild
    - visualstudio

stages:
- stage: Build
  jobs:
  - job: BuildArmTemplates
    displayName: "Build the ARM templates"
    workspace:
      clean: all
    pool: 'NCS - CI and CD'
    steps:
    - template: /AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        DotNetCoreVersion: 3.1.101
        PublishWebApp: true
        TestSuffix: UnitTests
  - job: BuildTestAndAnalyze
    pool:
      name: NCS - CI and CD
      demands:
      - msbuild
      - visualstudio
    steps:
    - template: AzureDevOpsTemplates\Build\StepTemplates\dfc-dotnetcore-build-sonar.yml@dfc-devops
      parameters:
        SolutionBaseName: $(SolutionBaseName)
        BuildPlatform: 'any cpu'
        BuildConfiguration: 'release'
        DotNetCoreVersion: 3.1.101
        PublishWebApp: true
        TestSuffix: UnitTests
