variables:
    SolutionBaseName: 'DFC.EventGridSubscriptions.ApiFunction'
    BuildPlatform: 'any cpu'
    BuildConfiguration: 'release'
    ArmTemplateRoot: '$(Build.SourcesDirectory)\Resources\ArmTemplates'

resources:
  repositories:
  - repository: self
  - repository: dfc-devops
    type: github
    name: SkillsFundingAgency/dfc-devops
    ref: refs/tags/v1.11.2
    endpoint: 'GitHub (ESFA)'

stages:
- stage: Build
  displayName: Build, Test and Analyze
  jobs:
  - job: BuildArmTemplates
    pool: 'NCS - CI and CD'
    steps:
    - template: AzureDevOpsTemplates/Build/StepTemplates/dfc-arm-build.yml@dfc-devops
      parameters:
        ArmTemplateRoot: $(ArmTemplateRoot)
        SolutionBaseName: $(SolutionBaseName)