variables:
- name: ReleaseEnvironmentName
  value: SIT
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: FunctionAppUrl
  value: https://dfc-dev-api-eventgridsubscriptions-fa.azurewebsites.net