variables:
- name: ReleaseEnvironmentName
  value: SIT
- name: aspTier
  value: Standard
- name: aspInstances
  value: 2
- name: aspSize
  value: 2
- name: FunctionAppUrl
  value: ''
- name: FunctionAppName
  value: dfc-sit-api-eventgridsubscriptions-fa
- name: RateLimitRenewalPeriod
  value: 1
- name: RateLimitRequests
  value: 20
- name: DeadLetterSubscriptionName
  value: dfc-sit-dead-letter-egs
- name: EventGridResourceGroup
  value: dfc-sit-stax-editor-rg
- name: EventGridTopicName
  value: dfc-sit-stax-egt
- name: ServicePrincipalName
  value: dfc-sit-api-eventgridsubscriptions
- name: DeadLetterSubscriptionEndPoint
  value: $(ApimProxyAddress)/composite-ui/subscription/api/DeadLetter/api/updates?subscription-key=$(ApimCompositeKey)